export const appData = [
  {
    name: '100 Questions - Youth',
    desc: 'An app to help you have better conversations with young people.',
    image: '/images/100q.png',
    apple: 'https://apps.apple.com/gb/app/100-questions-youth/id1387964565',
    android:
      'https://play.google.com/store/apps/details?id=uk.co.marktiddy.questions_youth_2',
    policy:
      '<p>Apps built by Mark Tiddy are apps provided to iOS app users and Google PlayStore users and are intended for use as they are.</p><p>This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my service.</p><p>If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.</p><h3>Information Collection and Use</h3><p>As part of using my apps I don’t require you to provide me directly with any personally identifiable information. I do not retain any data from your device.</p><p>Any free apps I create use third party services that may collect information used to identify you.</p><p><strong>The privacy policies of third party service prividers which may be used within my apps can be found below</strong></p><ul><li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank">AdMob</a></li><li><a href="https://firebase.google.com/policies/analytics" target="_blank">Firebase Analytics</a></li><li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li></ul><p><a href="https://policies.google.com/technologies/partner-sites?hl=en-GB&gl=uk" target="_blank">For details on how Google uses your data please click here</a></p><h3>Cookies</h3><p>Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory.</p><p>This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</p><h3>Changes to this privacy policy</h3><p>I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.</p><h3>Contact Us</h3><p>If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me via <a href="mailto:support@marktiddy.co.uk">support@marktiddy.co.uk</a>.</p>',
  },
  {
    name: 'This or That',
    desc: 'The quick-fire choice app that shows you how others have voted.',
    image: '/images/thisorthat.png',
    apple: 'http://apps.marktiddy.co.uk/this-or-that-app/',
    android: '',
    policy:
      '<p>Apps built by Mark Tiddy are apps provided to iOS app users and Google PlayStore users and are intended for use as they are.</p><p>This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my service.</p><p>If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.</p><h3>Information Collection and Use</h3><p>As part of using my apps I don’t require you to provide me directly with any personally identifiable information. I do not retain any data from your device.</p><p>Any free apps I create use third party services that may collect information used to identify you.</p><p><strong>The privacy policies of third party service prividers which may be used within my apps can be found below</strong></p><ul><li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank">AdMob</a></li><li><a href="https://firebase.google.com/policies/analytics" target="_blank">Firebase Analytics</a></li><li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li></ul><p><a href="https://policies.google.com/technologies/partner-sites?hl=en-GB&gl=uk" target="_blank">For details on how Google uses your data please click here</a></p><h3>Cookies</h3><p>Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory.</p><p>This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</p><h3>Changes to this privacy policy</h3><p>I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.</p><h3>Contact Us</h3><p>If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me via <a href="mailto:support@marktiddy.co.uk">support@marktiddy.co.uk</a>.</p>',
  },
  {
    name: 'LecDeck',
    desc:
      'Created with the Diocese of Bath and Wells and Diocese of Bristol this app is a lectionary-based youth work resource.',
    image: '/images/lecdeck.png',
    policy:
      '<p>Apps built by Mark Tiddy are apps provided to iOS app users and Google PlayStore users and are intended for use as they are.</p><p>This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my service.</p><p>If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.</p><h3>Information Collection and Use</h3><p>As part of using my apps I don’t require you to provide me directly with any personally identifiable information. I do not retain any data from your device.</p><p>Any free apps I create use third party services that may collect information used to identify you.</p><p><strong>The privacy policies of third party service prividers which may be used within my apps can be found below</strong></p><ul><li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank">AdMob</a></li><li><a href="https://firebase.google.com/policies/analytics" target="_blank">Firebase Analytics</a></li><li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li></ul><p><a href="https://policies.google.com/technologies/partner-sites?hl=en-GB&gl=uk" target="_blank">For details on how Google uses your data please click here</a></p><h3>Cookies</h3><p>Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory.</p><p>This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</p><h3>Changes to this privacy policy</h3><p>I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.</p><h3>Contact Us</h3><p>If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me via <a href="mailto:support@marktiddy.co.uk">support@marktiddy.co.uk</a>.</p>',
    apple: 'http://bit.ly/LecDeck-apple',
    android: 'http://bit.ly/lecdeck-android',
  },
  {
    name: "Catch 'em",
    desc: 'A fun game of matching coloured balls to coloured rings.',
    image: '/images/catch.png',
    apple: 'http://apps.marktiddy.co.uk/catch-em-game/',
    android: '',
    policy:
      '<p>Apps built by Mark Tiddy are apps provided to iOS app users and Google PlayStore users and are intended for use as they are.</p><p>This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my service.</p><p>If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.</p><h3>Information Collection and Use</h3><p>As part of using my apps I don’t require you to provide me directly with any personally identifiable information. I do not retain any data from your device.</p><p>Any free apps I create use third party services that may collect information used to identify you.</p><p><strong>The privacy policies of third party service prividers which may be used within my apps can be found below</strong></p><ul><li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank">AdMob</a></li><li><a href="https://firebase.google.com/policies/analytics" target="_blank">Firebase Analytics</a></li><li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li></ul><p><a href="https://policies.google.com/technologies/partner-sites?hl=en-GB&gl=uk" target="_blank">For details on how Google uses your data please click here</a></p><h3>Cookies</h3><p>Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory.</p><p>This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</p><h3>Changes to this privacy policy</h3><p>I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.</p><h3>Contact Us</h3><p>If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me via <a href="mailto:support@marktiddy.co.uk">support@marktiddy.co.uk</a>.</p>',
  },
  {
    name: 'Discuss LGBT*',
    desc:
      'An app to help youth leaders facilitate conversations with young people about LGBT*.',
    image: '/images/discusslgbt.png',
    policy:
      '<p>Apps built by Mark Tiddy are apps provided to iOS app users and Google PlayStore users and are intended for use as they are.</p><p>This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my service.</p><p>If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.</p><h3>Information Collection and Use</h3><p>As part of using my apps I don’t require you to provide me directly with any personally identifiable information. I do not retain any data from your device.</p><p>Any free apps I create use third party services that may collect information used to identify you.</p><p><strong>The privacy policies of third party service prividers which may be used within my apps can be found below</strong></p><ul><li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank">AdMob</a></li><li><a href="https://firebase.google.com/policies/analytics" target="_blank">Firebase Analytics</a></li><li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li></ul><p><a href="https://policies.google.com/technologies/partner-sites?hl=en-GB&gl=uk" target="_blank">For details on how Google uses your data please click here</a></p><h3>Cookies</h3><p>Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory.</p><p>This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</p><h3>Changes to this privacy policy</h3><p>I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.</p><h3>Contact Us</h3><p>If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me via <a href="mailto:support@marktiddy.co.uk">support@marktiddy.co.uk</a>.</p>',
    apple: 'https://apps.apple.com/ao/app/discuss-lgbtq/id1460389721',
    android:
      'https://play.google.com/store/apps/details?id=com.mtmedia.discusslgbt&hl=en_GB&gl=US',
  },
  {
    name: 'USA Tip Calculator',
    desc: 'A simple app to help you work out your tip when in the USA.',
    image: '/images/usatip.png',
    policy:
      '<p>Apps built by Mark Tiddy are apps provided to iOS app users and Google PlayStore users and are intended for use as they are.</p><p>This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my service.</p><p>If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.</p><h3>Information Collection and Use</h3><p>As part of using my apps I don’t require you to provide me directly with any personally identifiable information. I do not retain any data from your device.</p><p>Any free apps I create use third party services that may collect information used to identify you.</p><p><strong>The privacy policies of third party service prividers which may be used within my apps can be found below</strong></p><ul><li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank">AdMob</a></li><li><a href="https://firebase.google.com/policies/analytics" target="_blank">Firebase Analytics</a></li><li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li></ul><p><a href="https://policies.google.com/technologies/partner-sites?hl=en-GB&gl=uk" target="_blank">For details on how Google uses your data please click here</a></p><h3>Cookies</h3><p>Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory.</p><p>This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</p><h3>Changes to this privacy policy</h3><p>I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.</p><h3>Contact Us</h3><p>If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me via <a href="mailto:support@marktiddy.co.uk">support@marktiddy.co.uk</a>.</p>',
    apple: 'http://apps.marktiddy.co.uk/usa-tip-calculator-app/',
    android: '',
  },
];
